version: '3.9'

services:
  java_app:
    container_name: api_tp
    image: tp_lab:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=biblioteca
      - DATABASE_PASSWORD=biblioteca
    depends_on:
      - java_db
  java_db:
    container_name: baseDdatos
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
      POSTGRES_DB: postgres
